// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	AddBalance(ctx context.Context, arg AddBalanceParams) (Balance, error)
	AddClient(ctx context.Context, arg AddClientParams) (Client, error)
	AddInvoice(ctx context.Context, arg AddInvoiceParams) (Invoice, error)
	AddMessage(ctx context.Context, arg AddMessageParams) (Message, error)
	AddSystemConfig(ctx context.Context, arg AddSystemConfigParams) (SystemConfig, error)
	AddTemplate(ctx context.Context, arg AddTemplateParams) (Template, error)
	AddTransaction(ctx context.Context, arg AddTransactionParams) (ClientTransaction, error)
	AddUser(ctx context.Context, arg AddUserParams) (User, error)
	GetClient(ctx context.Context, email string) (Client, error)
	GetClientBalance(ctx context.Context, clientID string) (Balance, error)
	GetCreditedTransaction(ctx context.Context, arg GetCreditedTransactionParams) ([]ClientTransaction, error)
	GetInvoice(ctx context.Context, invoiceNumber uuid.UUID) (Invoice, error)
	GetInvoiceByMonth(ctx context.Context, arg GetInvoiceByMonthParams) (Invoice, error)
	GetLastMonthBalance(ctx context.Context, clientID string) (Balance, error)
	GetMessageById(ctx context.Context, id uuid.UUID) (Message, error)
	GetMessageWithPrefix(ctx context.Context, arg GetMessageWithPrefixParams) ([]Message, error)
	GetMessagesBySender(ctx context.Context, arg GetMessagesBySenderParams) ([]Message, error)
	GetSystemConfig(ctx context.Context, settingName string) (SystemConfig, error)
	GetUser(ctx context.Context, phone string) (User, error)
	LastMonthMessagePriceAndCount(ctx context.Context, clientID string) ([]LastMonthMessagePriceAndCountRow, error)
	ListAllBalance(ctx context.Context, arg ListAllBalanceParams) ([]Balance, error)
	ListAllClientInvoices(ctx context.Context, clientID string) ([]Invoice, error)
	ListAllClients(ctx context.Context, arg ListAllClientsParams) ([]Client, error)
	ListAllMessages(ctx context.Context, arg ListAllMessagesParams) ([]Message, error)
	ListAllSystemConfig(ctx context.Context) ([]SystemConfig, error)
	ListAllTemplates(ctx context.Context, arg ListAllTemplatesParams) ([]Template, error)
	ListClientInvoices(ctx context.Context, arg ListClientInvoicesParams) ([]Invoice, error)
	ListClientTemplates(ctx context.Context, arg ListClientTemplatesParams) ([]Template, error)
	ListClients(ctx context.Context) ([]Client, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	UpdateBalance(ctx context.Context, arg UpdateBalanceParams) (Balance, error)
	UpdateClient(ctx context.Context, arg UpdateClientParams) (Client, error)
	UpdateDeliveryStatus(ctx context.Context, arg UpdateDeliveryStatusParams) error
	UpdateSystemConfig(ctx context.Context, arg UpdateSystemConfigParams) (SystemConfig, error)
	UpdateTemplate(ctx context.Context, arg UpdateTemplateParams) (Template, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
