// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package db

import (
	"context"
)

type Querier interface {
	AddClient(ctx context.Context, arg AddClientParams) (Client, error)
	AddUser(ctx context.Context, arg AddUserParams) (User, error)
	GetClient(ctx context.Context, phone string) (Client, error)
	GetUser(ctx context.Context, phone string) (User, error)
	ListAllClients(ctx context.Context, arg ListAllClientsParams) ([]Client, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	UpdateClient(ctx context.Context, arg UpdateClientParams) (Client, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
