DROP TABLE IF EXISTS users;

DROP TABLE IF EXISTS clients;

DROP TABLE IF EXISTS templates;

DROP TABLE IF EXISTS messages;

DROP TABLE IF EXISTS balance;

DROP TABLE IF EXISTS system_config;

DROP TYPE IF EXISTS message_type;

DROP TABLE IF EXISTS invoice;

DROP TYPE IF EXISTS payment;