version: "2"

sql:
  - schema: "../internal/constant/query/schemas"
    queries: "../internal/constant/query/queries"
    engine: "postgresql"


    gen:
      go:
        package: "db"  
        out: "../internal/constant/model/db"
        emit_json_tags: true
        emit_prepared_queries: true
        emit_interface: true        
        emit_empty_slices: true
        sql_package: "pgx/v4"    
        overrides:
          - db_type: "pg_catalog.numeric"
            go_type: "github.com/shopspring/decimal.Decimal"
            nullable: false
          - db_type: "pg_catalog.numeric"
            go_type: "github.com/shopspring/decimal.Decimal"
            nullable: true
          - db_type: "string"
            go_type: "string"
            nullable: true
          - db_type: "bool"
            go_type: "bool"
            nullable: true
          - db_type: "bigint"
            go_type: "int64"
            nullable: false

          - db_type: "pg_catalog.timestamp"
            go_type:             
              import: "time"
              type: "Time"
              pointer: true
            nullable: true